server:
  port: 8087

spring:
  application:
    name: checkin-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: checkin_service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: checkin_service
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      url: ${REDIS_URL}

app:
  seed:
    enabled: false
  qr:
    key-id: ${QR_KEY_ID}
    private-key-base64: ${QR_PRIVATE_KEY_BASE64}
    public-key-base64: ${QR_PUBLIC_KEY_BASE64}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
